### ISSUE TITLE
A feature to delete questions answered by a user from the "View User Content" Page

### ISSUE THREAD

**Issue by HarshSaini800** [seahindeniz/BrainlyTools_Extension#141] opened 2020-06-23 12:00 UTC
![Variations](https://user-images.githubusercontent.com/67321824/85401127-1f5ac700-b577-11ea-99d8-b3541afde995.png)
A feature would allow to delete questions answered by a user would come in handy and make things much quicker.

**Comment by seahindeniz** [comment] 2020-07-16 15:05
Duplicate of #108

**Closed by seahindeniz** 2020-07-16 15:05 UTC
Labels: enhancement
