### ISSUE TITLE
"Delete All Comments" option in Mass-Manage Users

### ISSUE THREAD

**Issue by NisiDominus** [seahindeniz/BrainlyTools_Extension#317] opened 2020-11-26 17:43 UTC
A feature can be added that deletes all comments of the listed users at once.
![image](https://user-images.githubusercontent.com/47514611/100380352-bdbbee80-3027-11eb-950f-928aa573a655.png)

**Comment by remreozturk** [comment] 2020-12-05 08:40
It may be like this 👇
![image](https://user-images.githubusercontent.com/73168853/101238035-73ed9b00-36ee-11eb-9dff-88f5b9445599.png)

**Comment by NisiDominus** [comment] 2020-12-05 08:42
It may be like this 👇
![image](https://user-images.githubusercontent.com/47514611/101238105-eb232f00-36ee-11eb-80df-872cf6aceee9.png)

**Comment by seahindeniz** [comment] 2020-12-16 18:55
Duplicate of #27 

This one has requested before so, I'm closing it and will continue over there

**Closed by seahindeniz** 2020-12-16 18:55 UTC
Labels: 💎 enhancement
